### ISSUE TITLE
NameError: uninitialized constant Http::Exceptions::SocketError

### ISSUE THREAD

**Issue by epaulet** [rainforestapp/http-exceptions#12]
When using as a standalone gem, getting this error.

```
NameError: uninitialized constant Http::Exceptions::SocketError
Did you mean?  KeyError
	from /Users/Edward/Desktop/RainforestQA/http-exceptions/lib/http/exceptions.rb:10:in `<module:Exceptions>'
	from /Users/Edward/Desktop/RainforestQA/http-exceptions/lib/http/exceptions.rb:8:in `<module:Http>'
	from /Users/Edward/Desktop/RainforestQA/http-exceptions/lib/http/exceptions.rb:7:in `<top (required)>'
	from (irb):1:in `require_relative'
	from (irb):1
	from /Users/Edward/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
```

**Comment by epaulet** [comment]
Actually, this is easily fixed by moving around requires in my project as HTTParty already required `net/http` and `openssl`.
