### ISSUE TITLE
Unable to load with bundler 1.14.5

### ISSUE THREAD

**Issue by PikachuEXE** [rainforestapp/http-exceptions#14]
I am unable to load this gem with bundler 1.14.5

I also test with `bundle exec rspec` in this project and following error thrown:
```
/users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions/configuration.rb:5:in `<class:Configuration>': uninitialized constant Http::Exceptions::Configuration::SocketError (NameError)
Did you mean?  KeyError
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions/configuration.rb:3:in `<module:Exceptions>'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions/configuration.rb:2:in `<module:Http>'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions/configuration.rb:1:in `<top (required)>'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions.rb:2:in `require'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions.rb:2:in `<top (required)>'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/spec/spec_helper.rb:1:in `require'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/spec/spec_helper.rb:1:in `<top (required)>'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `require'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `block in requires='
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `each'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `requires='
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `each'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:99:in `setup'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/bin/rspec:22:in `load'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/bin/rspec:22:in `<main>'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

It might be bundler bug, not sure

**Comment by PikachuEXE** [comment]
I will submit a PR for a fix based on bundler/bundler#5474
